import { DataTable } from "./data-table";
import { Payment } from "../Validations";
import {columns} from "./columns"
const getData = async (): Promise<Payment[]> => {
  return [
    {
      id: "728ed521",
      userId: "U1001",
      amount: 134,
      status: "pending",
      email: "johndoe@gmail.com",
      FullName: "John Doe",
    },
    {
      id: "728ed522",
      userId: "U1002",
      amount: 124,
      status: "success",
      FullName: "Jane Doe",
      email: "janedoe@gmail.com",
    },
    {
      id: "728ed523",
      userId: "U1003",
      amount: 167,
      status: "success",
      FullName: "Mike Galloway",
      email: "mikegalloway@gmail.com",
    },
    {
      id: "728ed524",
      userId: "U1004",
      amount: 156,
      status: "failed",
      FullName: "Minerva Robinson",
      email: "minerbarobinson@gmail.com",
    },
    {
      id: "728ed525",
      userId: "U1005",
      amount: 145,
      status: "success",
      FullName: "Mable Clayton",
      email: "mableclayton@gmail.com",
    },
    {
      id: "728ed526",
      userId: "U1006",
      amount: 189,
      status: "pending",
      FullName: "Nathan McDaniel",
      email: "nathanmcdaniel@gmail.com",
    },
    {
      id: "728ed527",
      userId: "U1007",
      amount: 178,
      status: "success",
      FullName: "Myrtie Lamb",
      email: "myrtielamb@gmail.com",
    },
    {
      id: "728ed528",
      userId: "U1008",
      amount: 190,
      status: "success",
      FullName: "Leona Bryant",
      email: "leonabryant@gmail.com",
    },
    {
      id: "728ed529",
      userId: "U1009",
      amount: 134,
      status: "failed",
      FullName: "Aaron Willis",
      email: "aaronwillis@gmail.com",
    },
    {
      id: "728ed52a",
      userId: "U1010",
      amount: 543,
      status: "success",
      FullName: "Joel Keller",
      email: "joelkeller@gmail.com",
    },
    {
      id: "728ed52b",
      userId: "U1011",
      amount: 234,
      status: "pending",
      FullName: "Daniel Ellis",
      email: "danielellis@gmail.com",
    },
    {
      id: "728ed52c",
      userId: "U1012",
      amount: 345,
      status: "success",
            FullName: "Nathan McDaniel",

      email: "gordonkennedy@gmail.com",
    },
    {
      id: "728ed52d",
      userId: "U1013",
      amount: 335,
      status: "failed",
      FullName: "Emily Hoffman",
      email: "emilyhoffman@gmail.com",
    },
    {
      id: "728ed52e",
      userId: "U1014",
      amount: 664,
      status: "pending",
      FullName: "Jeffery Garrett",
      email: "jefferygarrett@gmail.com",
    },
    {
      id: "728ed52f",
      userId: "U1015",
      amount: 332,
      status: "success",
      FullName: "Ralph Baker",
      email: "ralphbaker@gmail.com",
    },
    {
      id: "728ed52g",
      userId: "U1016",
      amount: 413,
      status: "failed",
      FullName: "Seth Fields",
      email: "sethfields@gmail.com",
    },
    {
      id: "728ed52h",
      userId: "U1017",
      amount: 345,
      status: "pending",
      FullName: "Julia Webb",
      email: "juliawebb@gmail.com",
    },
    {
      id: "728ed52i",
      userId: "U1018",
      amount: 754,
      status: "success",
      FullName: "Gary Banks",
      email: "garybanks@gmail.com",
    },
    {
      id: "728ed52j",
      userId: "U1019",
      amount: 643,
      status: "failed",
      FullName: "Flora Chambers",
      email: "florachambers@gmail.com",
    },
    {
      id: "728ed52k",
      userId: "U1020",
      amount: 543,
      status: "pending",
      FullName: "Steve Hanson",
      email: "stevehanson@gmail.com",
    },
    {
      id: "728ed52l",
      userId: "U1021",
      amount: 324,
      status: "success",
      FullName: "Lola Robinson",
      email: "lolarobinson@gmail.com",
    },
    {
      id: "728ed52m",
      userId: "U1022",
      amount: 123,
      status: "pending",
      FullName: "Ethel Waters",
      email: "ethelwaters@gmail.com",
    },
    {
      id: "728ed52n",
      userId: "U1023",
      amount: 422,
      status: "failed",
      FullName: "Grace Edwards",
      email: "graceedwards@gmail.com",
    },
    {
      id: "728ed52o",
      userId: "U1024",
      amount: 712,
      status: "success",
      FullName: "Sallie Wong",
      email: "salliewong@gmail.com",
    },
    {
      id: "728ed52p",
      userId: "U1025",
      amount: 360,
      status: "success",
      FullName: "Bryan Gutierrez",
      email: "bryangutierrez@gmail.com",
    },
    {
      id: "728ed52q",
      userId: "U1026",
      amount: 454,
      status: "pending",
      FullName: "Erik Rice",
      email: "erikrice@gmail.com",
    },
    {
      id: "728ed52r",
      userId: "U1027",
      amount: 382,
      status: "success",
      FullName: "Jordan Atkins",
      email: "jordanatkins@gmail.com",
    },
    {
      id: "728ed52s",
      userId: "U1028",
      amount: 328,
      status: "failed",
      FullName: "Bill Brewer",
      email: "billbrewer@gmail.com",
    },
    {
      id: "728ed52t",
      userId: "U1029",
      amount: 250,
      status: "success",
      FullName: "Edwin Morris",
      email: "edwinmorris@gmail.com",
    },
    {
      id: "728ed52u",
      userId: "U1030",
      amount: 658,
      status: "success",
      FullName: "Harold Becker",
      email: "haroldbecker@gmail.com",
    },
    {
      id: "728ed52v",
      userId: "U1031",
      amount: 691,
      status: "success",
      FullName: "Hannah Rodriguez",
      email: "hannahrodriguez@gmail.com",
    },
    {
      id: "728ed52w",
      userId: "U1032",
      amount: 969,
      status: "success",
      FullName: "Zachary Beck",
      email: "zacharybeck@gmail.com",
    },
    {
      id: "728ed52x",
      userId: "U1033",
      amount: 617,
      status: "failed",
      FullName: "Frances Potter",
      email: "francespotter@gmail.com",
    },
    {
      id: "728ed52y",
      userId: "U1034",
      amount: 173,
      status: "success",
      FullName: "Raymond Murray",
      email: "raymondmurray@gmail.com",
    },
    {
      id: "728ed52z",
      userId: "U1035",
      amount: 843,
      status: "success",
      FullName: "Adam Sherman",
      email: "adamsherman@gmail.com",
    },
    {
      id: "728ed521f",
      userId: "U1036",
      amount: 914,
      status: "pending",
      FullName: "Anne Cruz",
      email: "annecruz@gmail.com",
    },
  ];
};

const PaymentsPage = async () => {
  const data = await getData();
  return (
    <div className="">
      <div className="mb-8 px-4 py-2 bg-secondary rounded-md">
        <h1 className="font-semibold">All Payments</h1>
      </div>
      <DataTable columns={columns} data={data}/>
    </div>
  );
};

export default PaymentsPage;