import type { Metadata } from "next";
import AppSidebar from "@/components/shared/SIdebar";
import { ThemeProvider } from "@/components/shared/provider/themeProvider";
import Navbar from "@/components/shared/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import Useprotectedroute from "@/hooks/Useprotectedroute";
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <div className="flex ">
      <Useprotectedroute>

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main className="w-full flex-1">
              <Navbar />
              <div className="px-4">{children}</div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </Useprotectedroute>
    </div>
  );
}